src/GestionUsuariosBundle/Entity/Usuario.php
<?php

namespace GestionUsuariosBundle\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Usuario
 *
 * @ORM\Table(name="usuarios")
 * @ORM\Entity(repositoryClass="GestionUsuariosBundle\Entity\UsuarioRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Usuario implements AdvancedUserInterface, \Serializable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=40)
     */
    private $username;
    
    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=140)
     */
    private $nombre;
    
    /**
     * @var string
     *
     * @ORM\Column(name="apellido", type="string", length=140)
     */
    private $apellido;
    
    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="clave", type="string", length=255)
     */
    private $clave;

    /**
     * @var boolean
     *
     * @ORM\Column(name="activo", type="boolean")
     */
    private $activo;

    /**
     * @var string
     *
    /**@ORM\Column(type="string", columnDefinition="ENUM('ROLE_USER', 'ROLE_ADMIN', 'ROLE_PAX', 'ROLE_SUPER_ADMIN')", nullable=false) 
     */
    private $role;
    
    /**
     * @ORM\ManyToMany(targetEntity="Mant\AlmacenBundle\Entity\Almacen")
     * @ORM\JoinTable(name="depositos_por_usuario",
     *      joinColumns={@ORM\JoinColumn(name="id_usuario", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="id_deposito", referencedColumnName="id")}
     *      )
     */
    private $depositos;    


    /**
     * @Assert\Count(
     *      max = 1,
     *      maxMessage = "Solo se permite asignar un role al usuario!"
     * )
     * @ORM\ManyToMany(targetEntity="RoleUsuario")
     * @ORM\JoinTable(name="roles_por_usuario",
     *      joinColumns={@ORM\JoinColumn(name="id_usuario", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="id_role", referencedColumnName="id")}
     *      )
     */
    private $roles;    

    public function __construct(){
        $this->activo=true;
        $this->depositos = new \Doctrine\Common\Collections\ArrayCollection();        
    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return Usuario
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set clave
     *
     * @param string $clave
     * @return Usuario
     */
    public function setClave($clave)
    {
        $this->clave = $clave;

        return $this;
    }

    /**
     * Get clave
     *
     * @return string 
     */
    public function getClave()
    {
        return $this->clave;
    }

    /**
     * Set activo
     *
     * @param boolean $activo
     * @return Usuario
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get activo
     *
     * @return boolean 
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set role
     *
     * @param string $role
     * @return Usuario
     */
    public function setRole($role)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get role
     *
     * @return string 
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Usuario
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set apellido
     *
     * @param string $apellido
     * @return Usuario
     */
    public function setApellido($apellido)
    {
        $this->apellido = $apellido;

        return $this;
    }

    /**
     * Get apellido
     *
     * @return string 
     */
    public function getApellido()
    {
        return $this->apellido;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Usuario
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }
    
    /**
    * @ORM\PrePersist
    */
    public function setActiveValue()
    {
        $this->activo = 1;
    }
    

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }
    
    
    public function getRoles()
    {
        return array($this->role);
    }
    
    public function getPassword()
    {
        return $this->clave;
    }
    
    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
        
    }
    
    /**
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->clave,
            $this->activo
        ));
    }
     
    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->clave,
            $this->activo
        ) = unserialize($serialized);
    }
    
    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()  
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->activo;
    }    
    
    public function __toString()
    {
        return $this->apellido.", ".$this->nombre;
    }

    /**
     * Add depositos
     *
     * @param \Mant\AlmacenBundle\Entity\Almacen $depositos
     * @return Usuario
     */
    public function addDeposito(\Mant\AlmacenBundle\Entity\Almacen $depositos)
    {
        $this->depositos[] = $depositos;

        return $this;
    }

    /**
     * Remove depositos
     *
     * @param \Mant\AlmacenBundle\Entity\Almacen $depositos
     */
    public function removeDeposito(\Mant\AlmacenBundle\Entity\Almacen $depositos)
    {
        $this->depositos->removeElement($depositos);
    }

    /**
     * Get depositos
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getDepositos()
    {
        return $this->depositos;
    }

    /**
     * Add roles
     *
     * @param \GestionUsuariosBundle\Entity\RoleUsuario $roles
     * @return Usuario
     */
    public function addRole(\GestionUsuariosBundle\Entity\RoleUsuario $roles)
    {
        $this->roles[] = $roles;

        return $this;
    }

    /**
     * Remove roles
     *
     * @param \GestionUsuariosBundle\Entity\RoleUsuario $roles
     */
    public function removeRole(\GestionUsuariosBundle\Entity\RoleUsuario $roles)
    {
        $this->roles->removeElement($roles);
    }
    
    public function getPermisos()
    {
        return $this->roles;
    }
    
    public function tieneRolDe($roles)
    {
        foreach ($roles as $role)
        {
            if ($this->roles->contains($role))
                return true;
        }
        return false;
    }
    
}

src/GestionUsuariosBundle/Resources/views/user/add.html.twig
{% include('ppal.html.twig') %}

<div class="container">
   <div class="col-md-6">
	{{ form_start(form, {'attr': {'novalidate': 'novalidate', 'role':'form'}})}}
	    <h3>Nuevo Usuario</h3>
		<div class="form-group">
			{{	form_label(form.username)	}}
			{{	form_widget(form.username, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.username) }}
			</span>
		</div>
		<div class="form-group">
			{{	form_label(form.nombre)	}}
			{{	form_widget(form.nombre, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.nombre) }}
			</span>
		</div>			
		<div class="form-group">
			{{	form_label(form.apellido)	}}
			{{	form_widget(form.apellido, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.apellido) }}
			</span>
		</div>		
		<div class="form-group">
			{{	form_label(form.email)	}}
			{{	form_widget(form.email, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.email) }}
			</span>
		</div>	
		<div class="form-group">
			{{	form_label(form.role)	}}
			{{	form_widget(form.role, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.role) }}
			</span>
		</div>	
		<div class="form-group">
			{{	form_label(form.clave)	}}
			{{	form_widget(form.clave, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.clave) }}
			</span>
		</div>			
		<p>
			{{ form_widget(form.save, {'attr':{'class' : 'btn btn-success'}})}}
		</p>

	{{ form_end(form)}} 
  </div>
</div>

src/GestionUsuariosBundle/Resources/views/user/home.html.twig
{% include('ppal.html.twig') %}
<div class="container">
  <strong>Bienvenido {{ app.user.nombre}}  </strong>
</div>

src/GestionUsuariosBundle/Resources/views/user/list.html.twig
{% extends('ppal.html.twig') %}
{% block stylesheets %}
 	{{ parent() }}
 	<link rel="stylesheet" href="{{ asset('bundles/mantalmacen/css/estilos.css')}}">
{% endblock %}
{% block body %}
{{ parent() }}

<div class="container">
	<div class="card">
	  <div class="card-header">
	     Usuarios existentes
	  </div>
	</div>
		{% for flash_message in app.session.flashbag.get('signerror') %}
			<div class="alert alert-danger" role="alert">
				{{ flash_message }}
			</div>
		{% endfor %}
		{% for flash_message in app.session.flashbag.get('signok') %}
			<div class="alert alert-success" role="alert">
				{{ flash_message }}
			</div>
		{% endfor %}		
		
				<table class="table table-striped table-bordered table-hover table-sm">
					<thead>
						<tr>
                            <th scope="col">Usuario</th>							
                            <th scope="col">Apellido</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Role</th>
                            <th scope="col">Ultimo Acceso</th>                            
                            <th></th>
						</tr>
					</thead>
					<tbody>
				        {% for user in users %}
                            <tr>
                                <td>{{ user.username }}</td>    
                                <td>{{ user.apellido | title }}</td>    
                                <td>{{ user.nombre | title }}</td>     
                                <td>{{ user.role | title }}</td>                                   
                                <td></td>
				                <td>	
				                	<div>
										{{ form_start(forms[user.id]) }}
										{{ form_widget(forms[user.id].view, {'attr':{'class' : 'btn btn-warning btn-sm sing estilo1'}}) }}
										{{ form_end(forms[user.id]) }}
									</div>
								</td>
                            </tr>
				        {% endfor %}
					</tbody>
				</table>
</div>

		
{% endblock %}
{% block javascripts %}
	{{ parent() }}
{% endblock %}

src/GestionUsuariosBundle/Resources/views/user/view.html.twig
{% extends('ppal.html.twig') %}
{% block stylesheets %}
 	{{ parent() }}
 	<link rel="stylesheet" href="{{ asset('bundles/mantalmacen/css/estilos.css')}}">
{% endblock %}
{% block body %}
{{ parent() }}

<div class="container">
	<div class="card">
	  <div class="card-header">
	     Apellido, Nombre:  {{ user }} <br>
	     Perfil: {{ user.role }}
	  </div>
	</div>
	
			{% for flash_message in app.session.flashbag.get('signerror') %}
			<div class="alert alert-danger" role="alert">
				{{ flash_message }}
			</div>
		{% endfor %}
		{% for flash_message in app.session.flashbag.get('signok') %}
			<div class="alert alert-success" role="alert">
				{{ flash_message }}
			</div>
		{% endfor %}	
	<div class="card-header">
	<span class="h6">Roles del usuario</span>
		<table class="table table-striped table-bordered table-hover table-sm">
					<thead>
						<tr>
                            <th scope="col">Role</th>							
                            <th>Accion</th>
						</tr>
					</thead>
					<tbody>
						{%  for rol in user.permisos %}
							<tr>
								<td class="col-6">
									{{ rol }}
								</td> 
								<td align="center" class="col-6">
										{{ form_start(formRoles[rol.id]) }}
										{{ form_widget(formRoles[rol.id].action, {'attr':{'class' : 'btn btn-warning btn-sm sing estilo1'}}) }}
										{{ form_end(formRoles[rol.id]) }}									
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
		{{ form_start(addRole) }}				
		<div class="row">
			<div class="col-4">
						{{ form_widget(addRole.roles , {'attr':{'class' : 'form-control'}})}}	
			</div>
			<div class="col-2">
						{{ form_widget(addRole.action, {'attr':{'class' : 'btn btn-success'}}) }}
			</div>
			
		</div>
		{{ form_end(addRole) }}	
	</div>
	<div class="card-header">
	<span class="h6">Depositos autorizados</span>
		<table class="table table-striped table-bordered table-hover table-sm">
					<thead>
						<tr>
                            <th scope="col">Deposito</th>							
                            <th>Accion</th>
						</tr>
					</thead>
					<tbody>
						{%  for rol in user.depositos %}
							<tr>
								<td class="col-6">
									{{ rol }}
								</td>
								<td align="center" class="col-6">
										{{ form_start(formDepos[rol.id]) }}
										{{ form_widget(formDepos[rol.id].action, {'attr':{'class' : 'btn btn-warning btn-sm sing estilo1'}}) }}
										{{ form_end(formDepos[rol.id]) }}									
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
		{{ form_start(addDepo) }}				
		<div class="row">
			<div class="col-4">
						{{ form_widget(addDepo.almacenes , {'attr':{'class' : 'form-control'}})}}	
			</div>
			<div class="col-2">
						{{ form_widget(addDepo.action, {'attr':{'class' : 'btn btn-success'}}) }}
			</div>
			
		</div>
		{{ form_end(addDepo) }}												
	</div>	
</div>

		
{% endblock %}
{% block javascripts %}
	{{ parent() }}
{% endblock %}