src/Mant/AlmacenBundle/Entity/ArticuloDeposito.php
<?php

namespace Mant\AlmacenBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ArticuloDeposito
 *
 * @ORM\Table(name="articulos_por_deposito")
 * @ORM\Entity(repositoryClass="Mant\AlmacenBundle\Entity\ArticuloDepositoRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class ArticuloDeposito
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;


    /**
    * @ORM\ManyToOne(targetEntity="Mant\AlmacenBundle\Entity\Articulo") 
    * @ORM\JoinColumn(name="id_articulo", referencedColumnName="id")
    */      
    private $articulo;

    /**
    * @ORM\ManyToOne(targetEntity="Mant\AlmacenBundle\Entity\Almacen") 
    * @ORM\JoinColumn(name="id_almacen", referencedColumnName="id")
    */      
    private $almacen;    

    /**
     * @var float
     *
     * @ORM\Column(name="sMin", type="float", nullable=false, options={"default": 0.0})
     */
    private $sMin = 0;

    /**
     * @var float
     *
     * @ORM\Column(name="sMax", type="float", nullable=true)
     */
    private $sMax;

    /**
     * @var float
     *
     * @ORM\Column(name="sActual", type="float", nullable=false, options={"default": 0.0})
     */
    private $sActual = 0;
     

    /**
     * @var float
     *
     * @ORM\Column(name="precioCompra", type="float", nullable=false, options={"default": 0.0})
     */
    private $precioCompra = 0;       ////se usa para calcular el precio de venta


    /**
     * @var float
     *
     * @ORM\Column(name="ultPrecioCompra", type="float", nullable=false, options={"default": 0.0})
     */
    private $ultPrecioCompra = 0;       


    /**
     * @var boolean
     *
     * @ORM\Column(name="activo", type="boolean", nullable=false, options={"default":true})
     */
    private $activo;   

    /**
     * @var float
     *
     * @ORM\Column(name="markup", type="float", nullable=false, options={"default": 0.0})
     */
    private $markup = 0;   
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }


    public function getPrecioVenta()
    {
        return ($this->precioCompra * (1+($this->markup/100)));
    }

    public function getPrecioVentaActualizado()
    {
        return ($this->ultPrecioCompra * (1+($this->markup/100)));
    }    
    /**
     * Set sMin
     *
     * @param float $sMin
     * @return ArticuloDeposito
     */
    public function setSMin($sMin)
    {
        $this->sMin = $sMin;

        return $this;
    }

    /**
     * Get sMin
     *
     * @return float 
     */
    public function getSMin()
    {
        return $this->sMin;
    }

    /**
     * Set sMax
     *
     * @param float $sMax
     * @return ArticuloDeposito
     */
    public function setSMax($sMax)
    {
        $this->sMax = $sMax;

        return $this;
    }

    /**
     * Get sMax
     *
     * @return float 
     */
    public function getSMax()
    {
        return $this->sMax;
    }

    /**
     * Set sActual
     *
     * @param float $sActual
     * @return ArticuloDeposito
     */
    public function setSActual($sActual)
    {
        $this->sActual = $sActual;

        return $this;
    }

    /**
     * Get sActual
     *
     * @return float 
     */
    public function getSActual()
    {
        return $this->sActual;
    }

    /**
     * Set precioCompra
     *
     * @param float $precioCompra
     * @return ArticuloDeposito
     */
    public function setPrecioCompra($precioCompra)
    {
        $this->precioCompra = $precioCompra;

        return $this;
    }

    /**
     * Get precioCompra
     *
     * @return float 
     */
    public function getPrecioCompra()
    {
        return $this->precioCompra;
    }


    /**
     * Set articulo
     *
     * @param \Mant\AlmacenBundle\Entity\Articulo $articulo
     * @return ArticuloDeposito
     */
    public function setArticulo(\Mant\AlmacenBundle\Entity\Articulo $articulo = null)
    {
        $this->articulo = $articulo;

        return $this;
    }

    /**
     * Get articulo
     *
     * @return \Mant\AlmacenBundle\Entity\Articulo 
     */
    public function getArticulo()
    {
        return $this->articulo;
    }

    /**
     * Set almacen
     *
     * @param \Mant\AlmacenBundle\Entity\Almacen $almacen
     * @return ArticuloDeposito
     */
    public function setAlmacen(\Mant\AlmacenBundle\Entity\Almacen $almacen = null)
    {
        $this->almacen = $almacen;

        return $this;
    }

    /**
     * Get almacen
     *
     * @return \Mant\AlmacenBundle\Entity\Almacen 
     */
    public function getAlmacen()
    {
        return $this->almacen;
    }

    /**
     * Set activo
     *
     * @param boolean $activo
     * @return ArticuloDeposito
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get activo
     *
     * @return boolean 
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->activo = true;
    }       

    public function updateStock($stock)
    {
        $this->sActual+= $stock;
    }

    /**
     * Set markup
     *
     * @param float $markup
     * @return ArticuloDeposito
     */
    public function setMarkup($markup)
    {
        $this->markup = $markup;

        return $this;
    }

    /**
     * Get markup
     *
     * @return float 
     */
    public function getMarkup()
    {
        return $this->markup;
    }

    /**
     * Set ultPrecioCompra
     *
     * @param float $ultPrecioCompra
     * @return ArticuloDeposito
     */
    public function setUltPrecioCompra($ultPrecioCompra)
    {
        $this->ultPrecioCompra = $ultPrecioCompra;

        return $this;
    }

    /**
     * Get ultPrecioCompra
     *
     * @return float 
     */
    public function getUltPrecioCompra()
    {
        return $this->ultPrecioCompra;
    }
}

src/Mant/AlmacenBundle/Entity/movimientos/Cliente.php
<?php

namespace Mant\AlmacenBundle\Entity\movimientos;

use Doctrine\ORM\Mapping as ORM;

/**
 * Cliente
 *
 * @ORM\Table(name="clientes")
 * @ORM\Entity(repositoryClass="Mant\AlmacenBundle\Entity\movimientos\ClienteRepository")
 */
class Cliente extends EnteComercial
{


	public function __toString()
	{
		return $this->getRazonSocial();
	}
}

src/Mant/AlmacenBundle/Entity/movimientos/ClienteRepository.php
<?php

namespace Mant\AlmacenBundle\Entity\movimientos;

use Doctrine\ORM\EntityRepository;

class ClienteRepository extends EntityRepository
{


}

src/Mant/AlmacenBundle/Entity/movimientos/ConceptoMovimiento.php
<?php

namespace Mant\AlmacenBundle\Entity\movimientos;

use Doctrine\ORM\Mapping as ORM;

/**
 * ConceptoMovimiento
 *
 * @ORM\Table(name="conceptos_movimiento")
 * @ORM\Entity(repositoryClass="Mant\AlmacenBundle\Entity\movimientos\ConceptoMovimientoRepository")
 */
class ConceptoMovimiento
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="concepto", type="string", length=150)
     */
    private $concepto;
    
    
    /**
     * @var string
     *
     * @ORM\Column(name="movAfectado", type="string", length=150)
     */
    private $movAfectado;
    
    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean")
     */
    private $dobleFirma;
        
        
    /**
    * @ORM\ManyToOne(targetEntity="GestionUsuariosBundle\Entity\RoleUsuario") 
    * @ORM\JoinColumn(name="id_role_firma_1", referencedColumnName="id")
    */   
    private $roleFirma1;

    /**
    * @ORM\ManyToOne(targetEntity="GestionUsuariosBundle\Entity\RoleUsuario") 
    * @ORM\JoinColumn(name="id_role_firma_2", referencedColumnName="id")
    */   
    private $roleFirma2;
    
    /**
    * @ORM\ManyToOne(targetEntity="GestionUsuariosBundle\Entity\RoleUsuario") 
    * @ORM\JoinColumn(name="id_role_carga_observacion", referencedColumnName="id")
    */   
    private $roleCargaObservacion; ///para el caso de los formularios que queden observados y se requiera la doble firma, indica cual es el role del usuario que debe introducior el comentario     

    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean")
     */
    private $observaFormulario;  ////para saber si marca el movimiento como observado
    
    /**
    * @ORM\ManyToOne(targetEntity="GestionUsuariosBundle\Entity\RoleUsuario") 
    * @ORM\JoinColumn(name="id_role_firma_autorizante", referencedColumnName="id")
    */   
    private $roleFirmaAutorizante;    ////en los casos como el de las OC que exceden el stock maximo, define cual es el role del usuario que debe autorizarla 
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set concepto
     *
     * @param string $concepto
     * @return ConceptoMovimiento
     */
    public function setConcepto($concepto)
    {
        $this->concepto = $concepto;

        return $this;
    }

    /**
     * Get concepto
     *
     * @return string 
     */
    public function getConcepto()
    {
        return $this->concepto;
    }
    
    public function __toString()
    {
        return $this->concepto;
    }

    /**
     * Set movAfectado
     *
     * @param string $movAfectado
     * @return ConceptoMovimiento
     */
    public function setMovAfectado($movAfectado)
    {
        $this->movAfectado = $movAfectado;

        return $this;
    }

    /**
     * Get movAfectado
     *
     * @return string 
     */
    public function getMovAfectado()
    {
        return $this->movAfectado;
    }

    /**
     * Set dobleFirma
     *
     * @param boolean $dobleFirma
     * @return ConceptoMovimiento
     */
    public function setDobleFirma($dobleFirma)
    {
        $this->dobleFirma = $dobleFirma;

        return $this;
    }

    /**
     * Get dobleFirma
     *
     * @return boolean 
     */
    public function getDobleFirma()
    {
        return $this->dobleFirma;
    }

    /**
     * Set roleFirma1
     *
     * @param \GestionUsuariosBundle\Entity\RoleUsuario $roleFirma1
     * @return ConceptoMovimiento
     */
    public function setRoleFirma1(\GestionUsuariosBundle\Entity\RoleUsuario $roleFirma1 = null)
    {
        $this->roleFirma1 = $roleFirma1;

        return $this;
    }

    /**
     * Get roleFirma1
     *
     * @return \GestionUsuariosBundle\Entity\RoleUsuario 
     */
    public function getRoleFirma1()
    {
        return $this->roleFirma1;
    }

    /**
     * Set roleFirma2
     *
     * @param \GestionUsuariosBundle\Entity\RoleUsuario $roleFirma2
     * @return ConceptoMovimiento
     */
    public function setRoleFirma2(\GestionUsuariosBundle\Entity\RoleUsuario $roleFirma2 = null)
    {
        $this->roleFirma2 = $roleFirma2;

        return $this;
    }

    /**
     * Get roleFirma2
     *
     * @return \GestionUsuariosBundle\Entity\RoleUsuario 
     */
    public function getRoleFirma2()
    {
        return $this->roleFirma2;
    }

    /**
     * Set observaFormulario
     *
     * @param boolean $observaFormulario
     * @return ConceptoMovimiento
     */
    public function setObservaFormulario($observaFormulario)
    {
        $this->observaFormulario = $observaFormulario;

        return $this;
    }

    /**
     * Get observaFormulario
     *
     * @return boolean 
     */
    public function getObservaFormulario()
    {
        return $this->observaFormulario;
    }
    
    public function userFirmaConcepto($usuario) ////consulta si el usuarui ouede firmar el concepto de acuerdo a su role
    {
        return ($usuario->getPermisos()->contains($this->roleFirma1) || $usuario->getPermisos()->contains($this->roleFirma2));
    }
    
    public function userAutorizaConcepto($usuario) ////consulta si el usuarui ouede autorizar el concepto de acuerdo a su role (Por ej las OC que exceden el stock maximo)
    {
        return ($usuario->getPermisos()->contains($this->roleFirmaAutorizante));
    }    

    /**
     * Set roleFirmaAutorizante
     *
     * @param \GestionUsuariosBundle\Entity\RoleUsuario $roleFirmaAutorizante
     * @return ConceptoMovimiento
     */
    public function setRoleFirmaAutorizante(\GestionUsuariosBundle\Entity\RoleUsuario $roleFirmaAutorizante = null)
    {
        $this->roleFirmaAutorizante = $roleFirmaAutorizante;

        return $this;
    }

    /**
     * Get roleFirmaAutorizante
     *
     * @return \GestionUsuariosBundle\Entity\RoleUsuario 
     */
    public function getRoleFirmaAutorizante()
    {
        return $this->roleFirmaAutorizante;
    }

    /**
     * Set roleCargaObservacion
     *
     * @param \GestionUsuariosBundle\Entity\RoleUsuario $roleCargaObservacion
     * @return ConceptoMovimiento
     */
    public function setRoleCargaObservacion(\GestionUsuariosBundle\Entity\RoleUsuario $roleCargaObservacion = null)
    {
        $this->roleCargaObservacion = $roleCargaObservacion;

        return $this;
    }

    /**
     * Get roleCargaObservacion
     *
     * @return \GestionUsuariosBundle\Entity\RoleUsuario 
     */
    public function getRoleCargaObservacion()
    {
        return $this->roleCargaObservacion;
    }
}

src/Mant/AlmacenBundle/Entity/movimientos/EntradaStock.php
<?php

namespace Mant\AlmacenBundle\Entity\movimientos;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * EntradaStock
 *
 * @ORM\Table(name="entrada_stock")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks() 
 */
class EntradaStock extends MovimientoStock
{
    /**
    * @ORM\ManyToOne(targetEntity="Mant\AlmacenBundle\Entity\Almacen") 
    * @ORM\JoinColumn(name="id_almacen_destino", referencedColumnName="id")
    * @Assert\NotBlank(message="El campo no puede permanecer en blanco!")    * 
    */   
    private $almacenDestino;   
    
    
    /**
     * @ORM\Column(name="numero", type="integer", nullable=true)
     * @ORM\GeneratedValue(strategy="AUTO")
     */    
    private $numero;

    /**
     * Set almacenDestino
     *
     * @param \Mant\AlmacenBundle\Entity\Almacen $almacenDestino
     * @return EntradaStock
     */
    public function setAlmacenDestino(\Mant\AlmacenBundle\Entity\Almacen $almacenDestino = null)
    {
        $this->almacenDestino = $almacenDestino;

        return $this;
    }

    /**
     * Get almacenDestino
     *
     * @return \Mant\AlmacenBundle\Entity\Almacen 
     */
    public function getAlmacenDestino()
    {
        return $this->almacenDestino;
    }
    
    
    public function getDescripcionFormulario()
    {
        return "Entrada de Stock";
    }
    

    /**
     * Set numero
     *
     * @param integer $numero
     * @return EntradaStock
     */
    public function setNumero($numero)
    {
        $this->numero = $numero;

        return $this;
    }

    /**
     * Get numero
     *
     * @return integer 
     */
    public function getNumero()
    {
        return $this->numero;
    }
    
    public function getInstance()
    {
        return 2;
    }
    
     public function getAlmacenOrigenData()
     {
         
     }
     
     public function getAlmacenDestinoData()
     {
        return $this->almacenDestino;    
     }
     
     public function updateArticleItem(ItemMovimiento $item)
     {
        $item->setPrecioTotal($item->getCantidad() * $item->getPrecioUnitario());
        $item->getArticulo()->updateStock($item->getCantidad());
       // $item->getArticulo()->setImporte($item->getPrecioUnitario());        
     }
     
     public function getProcesado()
     {

     }
     public function setProcesado($procesado)
     {

     }
     
     public function getTipoFormulario()
     {
         return 'inp';
     }
     
    public function getDepositoAAfectar()     
    {
        return $this->almacenDestino;
    }     
    
    public function getItemConfirmado()    
    {
        return true;
    }
    
    public function marcarProcesado($procesado){

    }
    
    public function movimientoConfirmado()
    {
        return true;
    }    
    
    public function verificarItem($item, $sRealOrigen, $sRealDestino, $stockEnTransito)
    {
        $st = $item->getArticulo()->getArticuloMarca()->getArticulo()->getStockArticuloAlmacen($this->almacenDestino);        
        if (($item->getCantidad() + $sRealDestino) > $st->getSMax()) ///verifica que el stock actual del articulo mas lo que se compra no supere el stock maximo
        {
            $result = array();
            $result['warning'] = true;
            $result['msge'] = 'La cantidad ingresada supera el stock maximo del producto! El movimiento quedara pendiente de autorizar ';
            return $result;
        }        
        return array('ok'=>true, 'warning'=>false, 'msge' => '');
    }    
    
    public function getDepositoAutorizante(){
        return null;
    }    
     
    public function getNameProveedor()
    {
        return "";
    }
    
    public function setAutorizacionFormulario()
    {
        $autorizado = true;
        $this->setAutorizado($autorizado);
    }    
    
    public function getControlaStockPorMarca()    
    {
        return false;
    }    

    public function generaMovimientoCtaCte()    
    {
        return false;
    }    

    public function getEnteComercial()
    {
        return null;
    }    

    public function deleteItemMovimiento($item)
    {
        
    }   

    public function actualizarItems()
    {

    }
}

src/Mant/AlmacenBundle/Resources/views/movimientos/addArticuloEntradaStock.html.twig
{% extends('ppal.html.twig') %}
{% block stylesheets %}
	{{ parent() }}
 	<link rel="stylesheet" href="{{ asset('bundles/mantalmacen/css/movimientos/addArticulosMovimiento.css')}}">
 	<link rel="stylesheet" href="{{ asset('bundles/mantalmacen/css/estilos.css')}}">
{% endblock %}

{% block body %}
	{{ parent() }}
<div class="container">
	
	<div class="card">
  <div class="card-header">
  	<div class='row'>
  		<div class="col-4">
  			Movimiento: {{ movimiento.getDescripcionFormulario | title }}
  		</div>
	    {% if movimiento.almacenOrigen is defined %}
	    	<div class="col-4">
	    		Origen:{{ movimiento.almacenOrigen }}
	    	</div>
	   	{% endif %}
	    {% if movimiento.almacenDestino is defined %}
	    	<div class="col-4">
	    		Destino:{{ movimiento.almacenDestino }}
	    	</div>
	   	{% endif %}	   	
  	</div>

  </div>
  <div class="card-body row">
    <span class="card-text col-4">Fecha: {{ movimiento.fecha | date("m/d/Y") }}</span>
	<span class="card-text col-4">Concepto: {% if movimiento.conceptoEntrada is defined %} {{ movimiento.conceptoEntrada | title }} {% endif %}</span>
  </div>
</div>
   <div class="card">
    <div class="card-body">
    	<h6>Articulos cargados al formulario</h6>
    	<table class="table table-striped table-hover table-bordered table-sm assign estilo1">
					<thead>
						<tr>
                            <th>Codigo</th>
                            <th>Descripcion</th>
                            <th>Cantidad</th>
                            <th>Unitario</th>           
                            <th>Total</th> 
                            <th>Quitar</th>
						</tr>
					</thead>
					<tbody>
				        {% for item in movimiento.items %}
                            <tr id="{{ item.id }}" class="trtable">
                                <td>{{ item.articulo.articulo.codigo|upper }}</td>
                                <td>{{ item.articulo.articulo.descripcion|title }}</td>
                                <td>{{ item.cantidad|number_format(2, '.', '')  }}</td>                                
                                <td>{{ item.precioUnitario|number_format(2, '.', '')  }}</td>       
                                <td>{{ item.precioTotal|number_format(2, '.', '')  }}</td>
                                <td><input type='button' class='btn btn-warning btn-sm delit' value='X' onClick='removeItem("{{path('mant_almacen_remove_item_movimiento', {'item' : item.id})}}", {{item.id}})';/> </td>
                            </tr>
				        {% endfor %}						
					</tbody>
		</table>
    </div>
  </div> 
  	{% for message in app.session.flashBag.get('error') %}
	    <div class="alert alert-danger" role="alert">
	        {{ message }}
	    </div>
	{% endfor %}
  {{ 	form_start(form, {'attr': {'id': 'form_add', 'novalidate': 'novalidate', 'role':'form'}}) }}
  <div class="card">
    <div class="card-body">
		<div class="row">
			<div class="col-md-2 rowdata ">{{ form_widget(form.codigo, { 'attr': {'placeholder': 'Codigo', 'class' : 'form-control rowvalue form-control-sm' } }) }}</div>
			<div class="col-md-3 rowdata">{{ form_widget(form.descripcion, { 'attr': {'placeholder': 'Descripcion', 'class' : 'form-control rowvalue form-control-sm' } }) }}</div>
			<div class="col-md-2 rowdata">{{ form_widget(form.marca, { 'attr': {'placeholder': 'Marca', 'class' : 'form-control rowvalue form-control-sm' } }) }}</div>			
			<div class="col-md-1 rowdata">{{ form_widget(form.cantidad, { 'attr': {'placeholder': 'Cant.', 'class' : 'form-control rowvalue form-control-sm cant-item' } }) }}</div>
			<div class="col-md-2 rowdata">{{ form_widget(form.unitario, { 'attr': {'placeholder': 'Unitario', 'class' : 'form-control rowvalue unitprice form-control-sm' } }) }}</div>
			<div class="col-md-1 rowdata">{{ form_widget(form.save, {'attr':{'class' : 'btn btn-success btn-add btn-sm'}}) }}</div>
			{{ form_widget(form.articulo, {'attr':{'data-id' : '0'}}) }}
		</div>
    </div>
  </div>  
 {{ form_end(form) }}
 	<span class="pull-right">
		<div class="row">
			<div class="col-2">
				{{ 	form_start(formcancel, {'attr': {'class':'frmcancel'}}) }}
				{{ form_widget(formcancel.cancel, {'attr':{'class' : 'btn btn-danger btn-add btncancel'}}) }}		
				{{ form_end(formcancel) }}
			</div>
			<div class="col-2">
				{{ 	form_start(formpausa, {'attr': {'class':'frmpaused'}})  }}
				{{ form_widget(formpausa.pausa, {'attr':{'class' : 'btn btn-warning btn-add btnpausa'}}) }}	
				{{ form_end(formpausa) }}	
			</div>			
			<div class="col-2">
				{{ 	form_start(formcierre, {'attr': {'class':'frmsend'}})  }}
				{{ form_widget(formcierre.save, {'attr':{'class' : 'btn btn-primary btn-add btnsend'}}) }}	
				{{ form_end(formcierre) }}	
			</div>
		</div>
	</span>
				
<span class="counter pull-left"></span>
<div>
	 <input type="text" class="search form-control col-4" placeholder="Descripcion/Codigo Barras">
				<table class="table table-striped table-hover table-bordered results table-sm table-fixed estilo1">
					<thead>
						<tr>
                            <th>Codigo</th>
                            <th>Descripcion</th>
                            <th>Codigo Barras</th>
                            <th>Stock Actual</th>
                            <th>Unitario</th>                            
						</tr>
    					<tr class="warning no-result">
      						<td colspan="7"><i class="fa fa-warning"></i> No se ecnontraron resultados</td>
    					</tr>						
					</thead>
					<tbody>
				        {% for articulo in articulos %}
                            <tr data-id="{{ articulo.id }}" class="trtable">
                                <td>{{ articulo.articulo.codigo|upper }}</td>
                                <td>{{ articulo.articulo.descripcion|title }}</td>
                                <td>{{ articulo.articulo.codBarras|title }}</td>                                
                                <td>{{ articulo.sActual  }}</td>
                                {%  if movimiento.instance == 4 %}
                                	<td>{{ articulo.precioCompra|number_format(2, '.', '')  }}</td>
                                {% else %}
                                	<td>{{ articulo.precioVenta|number_format(2, '.', '')  }}</td>
                                {% endif %}
                            </tr>
				        {% endfor %}
					</tbody>
				</table>
	</div>
</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('bundles/mantalmacen/js/movimientos/addArticulosMovimiento.js') }}"></script>
	
{% endblock %}

src/Mant/AlmacenBundle/Resources/views/movimientos/autorizarIngreso.html.twig
{% include('ppal.html.twig') %}
{% block stylesheets %}
 	<link rel="stylesheet" href="{{ asset('bundles/mantalmacen/css/estilos.css')}}">
{% endblock %}
<div class="container">
    <h4>Recepcionar Mercaderias</h4>
    	<div class="row">
			  {{ form_start(form, {'attr': {'novalidate': 'novalidate', 'role':'form', 'class':'form-inline'}})}}
			  <div class="col-sm-8">
				{{	form_widget(form.almacenes, {'attr':{'class' : 'form-control'}})}}
			  </div>
			  <div class="col-sm-4">
				{{ form_widget(form.save, {'attr':{'class' : 'btn btn-success'}})}}
			  </div>
			{{ form_end(form)}}
		</div>
		<br>
		
		{% if movimientos is defined %}
				<table class="table table-striped table-bordered table-hover table-sm estilo1">
					<thead>
						<tr>
							<th scope="col">Nro Comprobante</th>
                            <th scope="col">Fecha</th>
                            <th scope="col">Descripcion</th>
							<th scope="col">Deposito Origen</th>
                            <th scope="col">Cantidad Articulos</th>
                            <th scope="col">Usuario</th>
                            <th scope="col">Fecha Carga</th>
                            <th></th>
						</tr>
					</thead>
					<tbody>
				        {% for movimiento in movimientos %}
                            <tr data-id="{{ movimiento.id }}">
                            	<td>{{ "%06d" | format(movimiento.numeroComprobante) }}</td>      
                                <td>{{ movimiento.fecha|date("d/m/Y") }}</td>
                                <td>{{ movimiento.descripcionFormulario|title }}</td>
                                <td>{% if movimiento.almacenOrigen is defined %} {{ movimiento.almacenOrigen}} {% endif %}</td>
                                <td align="right">{{ movimiento.items.count }}</td>
                                <td class="actions">
                                	{{ movimiento.userAlta|title }}
				                </td>
				                <td>
				                	{{ movimiento.createdAt|date("d/m/Y - H:i") }}
				                </td>
				                <td>	
				                	<div>
				                		{{ 	form_start(forms[movimiento.id], {'attr': {'novalidate': 'novalidate', 'role':'form', 'class':'form-inline'}})  }}
										{{  form_widget(forms[movimiento.id].save, {'attr': {'class': 'btn btn-warning btn-sm estilo1'}}) }}
										{{  form_end(forms[movimiento.id]) }}
									</div>
								</td>
                            </tr>
				        {% endfor %}
					</tbody>
				</table>

		{% endif %}
{% block javascripts %}

	<script src="{{ asset('bundles/mantalmacen/js/movimientos/aprobarIngreso.js') }}"></script>

{% endblock %}
</div>