src/Mant/AlmacenBundle/Entity/ArticuloDeposito.php
<?php

namespace Mant\AlmacenBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ArticuloDeposito
 *
 * @ORM\Table(name="articulos_por_deposito")
 * @ORM\Entity(repositoryClass="Mant\AlmacenBundle\Entity\ArticuloDepositoRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class ArticuloDeposito
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;


    /**
    * @ORM\ManyToOne(targetEntity="Mant\AlmacenBundle\Entity\Articulo") 
    * @ORM\JoinColumn(name="id_articulo", referencedColumnName="id")
    */      
    private $articulo;

    /**
    * @ORM\ManyToOne(targetEntity="Mant\AlmacenBundle\Entity\Almacen") 
    * @ORM\JoinColumn(name="id_almacen", referencedColumnName="id")
    */      
    private $almacen;    

    /**
     * @var float
     *
     * @ORM\Column(name="sMin", type="float", nullable=false, options={"default": 0.0})
     */
    private $sMin = 0;

    /**
     * @var float
     *
     * @ORM\Column(name="sMax", type="float", nullable=true)
     */
    private $sMax;

    /**
     * @var float
     *
     * @ORM\Column(name="sActual", type="float", nullable=false, options={"default": 0.0})
     */
    private $sActual = 0;
     

    /**
     * @var float
     *
     * @ORM\Column(name="precioCompra", type="float", nullable=false, options={"default": 0.0})
     */
    private $precioCompra = 0;       ////se usa para calcular el precio de venta


    /**
     * @var float
     *
     * @ORM\Column(name="ultPrecioCompra", type="float", nullable=false, options={"default": 0.0})
     */
    private $ultPrecioCompra = 0;       


    /**
     * @var boolean
     *
     * @ORM\Column(name="activo", type="boolean", nullable=false, options={"default":true})
     */
    private $activo;   

    /**
     * @var float
     *
     * @ORM\Column(name="markup", type="float", nullable=false, options={"default": 0.0})
     */
    private $markup = 0;   
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }


    public function getPrecioVenta()
    {
        return ($this->precioCompra * (1+($this->markup/100)));
    }

    public function getPrecioVentaActualizado()
    {
        return ($this->ultPrecioCompra * (1+($this->markup/100)));
    }    
    /**
     * Set sMin
     *
     * @param float $sMin
     * @return ArticuloDeposito
     */
    public function setSMin($sMin)
    {
        $this->sMin = $sMin;

        return $this;
    }

    /**
     * Get sMin
     *
     * @return float 
     */
    public function getSMin()
    {
        return $this->sMin;
    }

    /**
     * Set sMax
     *
     * @param float $sMax
     * @return ArticuloDeposito
     */
    public function setSMax($sMax)
    {
        $this->sMax = $sMax;

        return $this;
    }

    /**
     * Get sMax
     *
     * @return float 
     */
    public function getSMax()
    {
        return $this->sMax;
    }

    /**
     * Set sActual
     *
     * @param float $sActual
     * @return ArticuloDeposito
     */
    public function setSActual($sActual)
    {
        $this->sActual = $sActual;

        return $this;
    }

    /**
     * Get sActual
     *
     * @return float 
     */
    public function getSActual()
    {
        return $this->sActual;
    }

    /**
     * Set precioCompra
     *
     * @param float $precioCompra
     * @return ArticuloDeposito
     */
    public function setPrecioCompra($precioCompra)
    {
        $this->precioCompra = $precioCompra;

        return $this;
    }

    /**
     * Get precioCompra
     *
     * @return float 
     */
    public function getPrecioCompra()
    {
        return $this->precioCompra;
    }


    /**
     * Set articulo
     *
     * @param \Mant\AlmacenBundle\Entity\Articulo $articulo
     * @return ArticuloDeposito
     */
    public function setArticulo(\Mant\AlmacenBundle\Entity\Articulo $articulo = null)
    {
        $this->articulo = $articulo;

        return $this;
    }

    /**
     * Get articulo
     *
     * @return \Mant\AlmacenBundle\Entity\Articulo 
     */
    public function getArticulo()
    {
        return $this->articulo;
    }

    /**
     * Set almacen
     *
     * @param \Mant\AlmacenBundle\Entity\Almacen $almacen
     * @return ArticuloDeposito
     */
    public function setAlmacen(\Mant\AlmacenBundle\Entity\Almacen $almacen = null)
    {
        $this->almacen = $almacen;

        return $this;
    }

    /**
     * Get almacen
     *
     * @return \Mant\AlmacenBundle\Entity\Almacen 
     */
    public function getAlmacen()
    {
        return $this->almacen;
    }

    /**
     * Set activo
     *
     * @param boolean $activo
     * @return ArticuloDeposito
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get activo
     *
     * @return boolean 
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->activo = true;
    }       

    public function updateStock($stock)
    {
        $this->sActual+= $stock;
    }

    /**
     * Set markup
     *
     * @param float $markup
     * @return ArticuloDeposito
     */
    public function setMarkup($markup)
    {
        $this->markup = $markup;

        return $this;
    }

    /**
     * Get markup
     *
     * @return float 
     */
    public function getMarkup()
    {
        return $this->markup;
    }

    /**
     * Set ultPrecioCompra
     *
     * @param float $ultPrecioCompra
     * @return ArticuloDeposito
     */
    public function setUltPrecioCompra($ultPrecioCompra)
    {
        $this->ultPrecioCompra = $ultPrecioCompra;

        return $this;
    }

    /**
     * Get ultPrecioCompra
     *
     * @return float 
     */
    public function getUltPrecioCompra()
    {
        return $this->ultPrecioCompra;
    }
}

src/Mant/AlmacenBundle/Controller/VentasController.php
<?php

namespace Mant\AlmacenBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Mant\AlmacenBundle\Entity\movimientos\EntradaStock;
use Mant\AlmacenBundle\Entity\movimientos\SalidaStock;
use Mant\AlmacenBundle\Entity\movimientos\TransferenciaStock;
use Mant\AlmacenBundle\Entity\movimientos\ConsumoStock;
use Mant\AlmacenBundle\Form\movimientos\EntradaStockType;
use Mant\AlmacenBundle\Form\movimientos\SalidaStockType;
use Mant\AlmacenBundle\Form\movimientos\ConsumoStockType;
use Mant\AlmacenBundle\Form\movimientos\TransferenciaStockType;
use Mant\AlmacenBundle\Entity\movimientos\ItemMovimiento;
use Symfony\Component\HttpFoundation\JsonResponse;
use Mant\AlmacenBundle\Entity\AlmacenRepository;
use Mant\AlmacenBundle\Entity\opciones\NumeracionFormulario;
use Mant\AlmacenBundle\Entity\movimientos\MovimientoStockRepository;
use Mant\AlmacenBundle\Entity\movimientos\NotaPedidoRepository;
use Mant\AlmacenBundle\Entity\movimientos\FacturaVenta;
use Mant\AlmacenBundle\Entity\finanzas\CuentaCorriente;
use Mant\AlmacenBundle\Entity\finanzas\MovimientoDebito;
use Mant\AlmacenBundle\Entity\movimientos\OrdenCompra;
use Mant\AlmacenBundle\Entity\movimientos\Cliente;
use Mant\AlmacenBundle\Form\movimientos\ClienteType;
use Mant\AlmacenBundle\Form\movimientos\OrdenCompraType;
use Mant\AlmacenBundle\Form\movimientos\FacturaVentaType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Validation;
use Symfony\Component\Security\Core\Validator\Constraints as SecurityAssert;
use GestionUsuariosBundle\Entity\VerificaClave;

//use Symfony\Component\Validator\Validation;
class VentasController extends Controller
{
    public function facturaVentaAction()
    {
        $factura = new FacturaVenta();
        $form = $this->getFormFacturaVenta($factura);
        return $this->render('MantAlmacenBundle:movimientos:facturaVenta.html.twig', array('form'=>$form->createView())); 
    }

    private function getFormFacturaVenta($movimiento)
    {
        return $this->createForm(new FacturaVentaType(), $movimiento, array('action'=>$this->generateUrl('mant_almacen_factura_venta_procesar'), 'method'=>'POST'));
    }

    public function facturaVentaProcesarAction(Request $request)
    {
        $factura = new FacturaVenta();
        $form = $this->getFormFacturaVenta($factura);
        $form->handleRequest($request);
        if ($form->isValid())
        {
            $em = $this->getDoctrine()->getManager();
            $user = $this->getUser();
            $factura->setUserAlta($user);            
            $em->persist($factura);
            $em->flush();
            return $this->redirectToRoute('mant_almacen_factura_venta_add_item', array('fact' => $factura->getId()));            
        }
        return $this->render('MantAlmacenBundle:movimientos:facturaVenta.html.twig', array('form'=>$form->createView()));         
    }

    public function facturaVentaAddItemAction($fact)
    {
        $em = $this->getDoctrine()->getManager();
        $factura = $em->find('MantAlmacenBundle:movimientos\FacturaVenta', $fact);
        if (!$factura){
            $this->addFlash('error',"Factura inexistente!!");
            return $this->redirectToRoute('mant_almacen_factura_venta');            
        }
        $repository = $em->getRepository('MantAlmacenBundle:movimientos\MovimientoStock');
        $notas = $this->getFormLoadNotaPedido($factura->getCliente(), $factura->getId());
        $form = $this->createFormActionFacturaVenta($factura->getId(), 'mant_almacen_action_factura_venta', 'POST');
        return $this->render('MantAlmacenBundle:ventas:addItemFacturaVenta.html.twig', array('factura' => $factura, 'notas' => $notas->createView(), 'form' => $form->createView()));
    }

    private function getFormLoadNotaPedido($cliente, $idFact)
    {
        $cli = $cliente;
        return $this->createFormBuilder()
                    ->add('notaspedido', 'entity', array('class' => 'MantAlmacenBundle:movimientos\NotaPedido',
                                            'query_builder' => function(NotaPedidoRepository $er) use ($cli){
                                                                                                return $er->createQueryBuilder('u')
                                                                                                        ->where('u.cliente = :cliente AND u.confirmado = :confirmado AND u.facturado = :facturado')
                                                                                                        ->setParameter('cliente', $cli)
                                                                                                        ->setParameter('confirmado', true)
                                                                                                        ->setParameter('facturado', false);
                                                                                             }))  
                    ->add('factura', 'hidden', array('data' => $idFact))
                    ->add('save', 'submit', array('label'=>'Ver Detalle'))
                    ->setAction($this->generateUrl('mant_almacen_show_items_nota_pedido'))                    
                    ->getForm();      
    }

    public function showItemsNotaPedidoAction(Request $request)
    {
        if ($request->isXmlHttpRequest())
        {
            try{
                $var = $request->request->get("form");
                
                $em = $this->getDoctrine()->getManager();
                $repository = $em->getRepository('MantAlmacenBundle:movimientos\MovimientoStock');
                $nota = $repository->find($var['notaspedido']);
                $items = $repository->getItemsPendientesFactrarNotasPedido($nota);
                $forms = array();
                foreach ($items as $item) {
                    $forms[$item['item']->getId()] = $this->getFormAddItemNPFactura($item['item'], $item['cantidad'], $var['factura'])->createView();
                }
                return $this->render('MantAlmacenBundle:ventas:showItemsNP.html.twig', array('items' => $items, 'forms' => $forms));
            }
            catch (\Exception $e) {return new Response($e->getMessage());}
        }    
        return new Response("holaaaaaaaaaaaaa");    
    }

    private function createFormActionFacturaVenta($id, $url, $method)
    {
        return $this->createFormBuilder()
                    ->add('save', 'submit', array('label' => 'Guardar Formulario'))
                    ->add('cancel', 'submit', array('label' => 'Eliminar Formulario'))
                    ->add('pausa', 'submit', array('label' => 'Pausar Formulario'))
                    ->add('accion', 'hidden')
                    ->setMethod($method)
                    ->setAction($this->generateUrl($url, array('mov' => $id)))
                    ->getForm();
    }    

    public function actionFacturaVentaAction($mov, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository('MantAlmacenBundle:movimientos\MovimientoStock');
        $factura = $repository->find($mov);
        if ($factura->getConfirmado()){
            $this->addFlash('error',"La fcatura se encuentra ya finalizada!!");
            return $this->redirectToRoute('mant_almacen_factura_venta');            
        }
        $form = $this->createFormActionFacturaVenta($mov, 'mant_almacen_action_factura_venta', 'POST');
        $form->handleRequest($request);
        $data = $form->getData();
        if ($data['accion'] == 'p')
        {
            $this->addFlash('response',"La fcatura se ha pausado exitosamente!!");
            return $this->redirectToRoute('mant_almacen_factura_venta');
        }
        elseif ($data['accion'] == 'c')
        {
            foreach ($factura->getItems() as $item) {
                $factura->deleteItemMovimiento($item);
            }
            $em->remove($factura);
            $em->flush();
            $this->addFlash('response',"La fcatura se ha eliminado exitosamente!!");
            return $this->redirectToRoute('mant_almacen_factura_venta');
        }
        elseif ($data['accion'] == 's')
        {
            /////////recupera el proximo numero de comprobante////////////////
            $options = $repository->getNumeroComprobante($factura->getTipoFormulario(), $factura->getDepositoAAfectar());
            $numero = 1;
            if (!$options){
                $options = new NumeracionFormulario();
                $options->setFormulario($factura->getTipoFormulario());
                $options->setDeposito($factura->getDepositoAAfectar());
                $em->persist($options);
            }
            else{
                $numero = $options->getProxNumero();
            }
            $factura->setNumeroComprobante($numero);
            $factura->actualizarItems();
            $numero++;
            $options->setProxNumero($numero);
            ///////////fin recupero numero comprobante///////////////////////   
            $factura->setConfirmado(true);
            $repository = $em->getRepository('MantAlmacenBundle:finanzas\CuentaCorriente');
            $ctaCte = $repository->ctaCteEnteComercial($factura->getCliente());
            if (!$ctaCte){
                $ctaCte = new CuentaCorriente();
                $ctaCte->setEnte($factura->getCliente());
                $em->persist($ctaCte);
            }
            $debito = new MovimientoDebito();
            $debito->setMonto($factura->getImporteTotal());
            $debito->setDetalle($factura->getDescripcionFormulario()." ".$factura->getNumeroComprobante());
            $debito->setMovimientoStock($factura);
            $debito->setCtacte($ctaCte);
            $em->persist($debito);  
            $em->flush();           

src/Mant/AlmacenBundle/Resources/views/ventas/addCliente.html.twig
{% include('ppal.html.twig') %}

<div class="container">
   <div class="col-md-6">
	{{ form_start(form, {'attr': {'novalidate': 'novalidate', 'role':'form'}})}}
	    <h3>Nuevo Cliente</h3>   
		<div class="form-group">
			{{	form_label(form.ente.razonSocial)	}}
			{{	form_widget(form.ente.razonSocial, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.ente.razonSocial) }}
			</span>
		</div>
		<div class="form-group">
			{{	form_label(form.ente.cuit)	}}
			{{	form_widget(form.ente.cuit, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.ente.cuit) }}
			</span>
		</div>			
		<div class="form-group">
			{{	form_label(form.ente.telefono)	}}
			{{	form_widget(form.ente.telefono, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.ente.telefono) }}
			</span>
		</div>		

		<div class="form-group">
			{{	form_label(form.ente.mail)	}}
			{{	form_widget(form.ente.mail, {'attr':{'class' : 'form-control'}})}}
			<span class="text-danger">
				{{ form_errors(form.ente.mail) }}
			</span>
		</div>			
		<p>
			{{ form_widget(form.save, {'attr':{'class' : 'btn btn-success'}})}}
		</p>

	{{ form_end(form)}} 
  </div>
</div>

src/Mant/AlmacenBundle/Resources/views/ventas/addItemFacturaVenta.html.twig
{% extends('ppal.html.twig') %}
{% block stylesheets %}
	{{ parent() }}
 	<link rel="stylesheet" href="{{ asset('bundles/mantalmacen/css/movimientos/addArticulosMovimiento.css')}}">
 	<link rel="stylesheet" href="{{ asset('bundles/mantalmacen/css/estilos.css')}}">
{% endblock %}

{% block body %}
	{{ parent() }}
<div class="container">
	
	<div class="card">
  <div class="card-header">
  	<div class='row'>
  		<div class="col-2">
  			{{ factura.getDescripcionFormulario | title }}
  		</div>
	    <div class="col-3">
	    	{{ factura.almacenOrigen }}
	    </div>
	    <div class="col-4">
	    	Cliente: {{ factura.cliente }}
	    </div>
		<div class="col-3">
			Fecha: {{ factura.fecha | date("m/d/Y") }}
		</div>
  	</div>

  </div>
</div>
   <div class="card">
    <div class="card-body">
    	<h6>Items cargados</h6>
    	<table class="table table-striped table-hover table-bordered table-sm assign estilo1">
					<thead>
						<tr>
                            <th>Descripcion</th>
                            <th>Cantidad</th>
                            <th>Costo Unitario</th>
                            <th>Unitario</th>           
                            <th>Total</th> 
                            <th>Quitar</th>
						</tr>
					</thead>
					<tbody>
				        {% for item in factura.items %}
                            <tr id="{{ item.id }}" class="trtable">
                                <td>{{ item.articulo.articulo.descripcion|title }}</td>
                                <td>{{ item.cantidad|number_format(2, '.', '')  }}</td>         
								<td>{{ item.costo|number_format(2, '.', '')  }}</td>                                                             
                                <td>{{ item.precioUnitario|number_format(2, '.', '')  }}</td>       
                                <td>{{ item.precioTotal|number_format(2, '.', '')  }}</td>
                                <td><a class='btn btn-danger btn-sm delit' href="{{path('mant_almacen_remove_item_movimiento', {'item' : item.id})}}">x</a> </td>
                            </tr>
				        {% endfor %}						
					</tbody>
		</table>
    </div>
  </div> 
  	{% for message in app.session.flashBag.get('error') %}
	    <div class="alert alert-danger" role="alert">
	        {{ message }}
	    </div>
	{% endfor %}
	
	  <div class="card">
	    <div class="card-body">
			  <div class="form-group">
					{{ 	form_start(notas, {'attr': {'class':'view row'}}) }}
					{{	form_widget(notas.notaspedido, {'attr':{'class' : 'form-control col-10'}})}}
					{{ form_widget(notas.save, {'attr':{'class' : 'btn btn-success btn-add col-2'}}) }}		
					{{ form_end(notas) }}
			  </div>
			  <div id="detalle">

			  </div>			  	    		
	    </div>
	  </div>  


		{{ 	form_start(form, {'attr': {'class':'formAction'}}) }}
		<div class="row">
				<div class="col-2">{{ form_widget(form.cancel, {'attr':{'class' : 'btn btn-danger btn-action', 'data-id':'c', 'data-msge':'Eliminar'}}) }}	</div>
				<div class="col-2">{{ form_widget(form.pausa, {'attr':{'class' : 'btn btn-warning btn-action', 'data-id':'p', 'data-msge':'Pausar'}}) }}</div>
				<div class="col-2">{{ form_widget(form.save, {'attr':{'class' : 'btn btn-primary btn-action', 'data-id':'s', 'data-msge':'Guardar'}}) }}</div>			
		</div>
		{{ form_end(form) }}	
</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	<script type="text/javascript">		
		$(document).ready(function(){
									$('.view').submit(function(event){			
																		$('#detalle').html('<div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>');													
																		event.preventDefault();
																		
																		var form = $(this);
																		$.post(form.attr('action'), 
																			   form.serialize(),
																			   function(data){
																			   					$('#detalle').html(data);
																			   });																	
									});
									$('.delit').click(function(event){						
																		event.preventDefault();
																		var a = $(this);
															            bootbox.confirm({
															                message: "Seguro quitar el item de la factura?",
															                buttons: {
															                    confirm: {
															                        label: 'Si',
															                        className: 'btn-success'
															                    },
															                    cancel: {
															                        label: 'No',
															                        className: 'btn-danger'
															                    }
															                },
															                callback: function (result) {
															                    if (result == true){											
																					$.post(a.attr('href'), 
																						   function(data){
																						   					if (data.status)
																						   						location.reload();
																						   					else
																						   						alert(data.message);
																						   });	
																				}
																			}
																		});
																	});		

								   $('.btn-action').click(function(event){
								   											event.preventDefault();
								   											var btn = $(this);
								   											$('#form_accion').val(btn.data('id'));
																            bootbox.confirm({
																                message: "Seguro "+btn.data('msge')+" la factura?",
																                buttons: {
																                    confirm: {
																                        label: 'Si',
																                        className: 'btn-success'
																                    },
																                    cancel: {
																                        label: 'No',
																                        className: 'btn-danger'
																                    }
																                },
																                callback: function (result) {
																                    if (result == true){											
																                    	$('.formAction').submit();
																					}
																				}
																			});
								   });							
		});
	</script>
	
{% endblock %}

src/Mant/AlmacenBundle/Resources/views/ventas/listaArticulosChange.html.twig
{% extends('ppal.html.twig') %}
{% block stylesheets %}
 	<link rel="stylesheet" href="{{ asset('bundles/mantalmacen/css/estilos.css')}}">
 	{{ parent() }}
{% endblock %}
{% block body %}
{{ parent() }}
<div class="container">
   <div>
   	<div><h4>Actualizar lista precios</h4></div>
	{{ form_start(form, {'attr': {'novalidate': 'novalidate', 'role':'form'}})}}
		<div class="form-group row">
			<div class="col-6">
						{{	form_widget(form.deposito , {'attr':{'class' : 'form-control'}})}}
						<span class="text-danger">
							{{ form_errors(form.deposito ) }}
						</span>
			</div>
			<div class="col-3">
				{{ form_widget(form.save, {'attr':{'class' : 'btn btn-success'}})}}
			</div>			
		</div>



	{{ form_end(form)}} 
  </div>
{% if articulos is defined %}
	<input type="text" class="search form-control col-4" id="search" placeholder="Codigo/Descripcion">
	<table class="table table-striped table-hover table-bordered results table-sm estilo1">
		<thead>
			<tr>
	            <th>Descripcion</th>
	            <th>Cod. Barras</th>
	            <th>Precio Actual Calculo</th>
	            <th>Precio Venta Actual</th>	            
	            <th>Nuevo Precio Compra</th>	    
	            <th>Precio Venta Actualizado</th>	  
	            <th>Actualizar</th>       
			</tr>
		</thead>
		<tbody>
	        {% for articulo in articulos %}
	            <tr class="finder">
	                <td>{{ articulo.articulo.descripcion|title }}</td>
	                <td>{{ articulo.articulo.codBarras|upper }}</td>	                
	                <td class="text-right">{{ articulo.precioCompra|number_format(2, '.', '')  }}</td>	   
	                <td class="text-right">{{ articulo.precioVenta|number_format(2, '.', '')  }}</td>	   	                
	                <td class="text-right">{{ articulo.ultPrecioCompra|number_format(2, '.', '')  }}</td>
	                <td class="text-right">{{ articulo.precioVentaActualizado|number_format(2, '.', '')  }}</td>
	                <td><a href="{{path("mant_almacen_update_price",{'id': articulo.id})}}" class="btn btn-warning btn-sm action">Actualizar</a></td>
	            </tr>
	        {% endfor %}
		</tbody>
	</table>  
{% endif %}
</div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
	<script src="{{ asset('bundles/mantalmacen/js/listArticles.js') }}"></script>
	<script>
		$(document).ready(function(){
			$('.action').click(function(event){
												event.preventDefault();
												var a = $(this);
						                       bootbox.confirm({
					                                            message: "Seguro realizar la modificacion?",
					                                            buttons: {
					                                                confirm: {
					                                                    label: 'Si',
					                                                    className: 'btn-success'
					                                                },
					                                                cancel: {
					                                                    label: 'No',
					                                                    className: 'btn-danger'
					                                                }
					                                            },
					                                            callback: function (result) {
					                                                if (result == true){
																		$.post(a.attr('href'), {a:0}, function(data){
																			if (data.status)
																			{
																				location.reload();
																			}
																			else{
																				alert(data.msge);
																			}
																		});
					                                                }
					                                            }
					                                        });  


			});
		});
	</script>
{% endblock %}

src/Mant/AlmacenBundle/Resources/views/ventas/showItemsNP.html.twig
<div class="container">
   <div class="card">
    <div class="card-body">
    	<h6>Items Pedidos</h6>
    	<table class="table table-striped table-hover table-bordered table-sm assign estilo1">
					<thead>
						<tr>
                            <th>Codigo</th>
                            <th>Descripcion</th>
                            <th>Cantidad</th>
                            <th>Unitario</th>           
                            <th>Total</th> 
                            <th>
                            	<div class="row">
                            		<div class="col-4">Cantidad</div>
                            		<div class="col-4">Precio Unitario</div>
                            		<div class="col-4">Agregar</div>
                            	</div>
                            </th>
						</tr>
					</thead>
					<tbody>
				        {% for item in items %}
                            <tr id="{{ item.item.id }}" class="trtable">
                                <td>{{ item.item.articulo.articulo.codigo|upper }}</td>
                                <td>{{ item.item.articulo.articulo.descripcion|title }}</td>
                                <td>{{ item.item.cantidad|number_format(2, '.', '')  }}</td>                                
                                <td>{{ item.item.precioUnitario|number_format(2, '.', '')  }}</td>       
                                <td>{{ item.item.precioTotal|number_format(2, '.', '')  }}</td>
                                <td>
									{{ 	form_start(forms[item.item.id], {'attr': {'class':'fact'}}) }}
									<div class="form-row">
									{{	form_widget(forms[item.item.id].cantidad, {'attr':{'class' : 'form-control form-control-sm col-4'}})}}
									{{	form_widget(forms[item.item.id].unitario, {'attr':{'class' : 'form-control form-control-sm col-4'}})}}									
									{{ form_widget(forms[item.item.id].add, {'attr':{'class' : 'btn btn-success btn-add col-4 btn-sm'}}) }}	
									</div>	
									{{ form_end(forms[item.item.id]) }}
                                </td>
                            </tr>
				        {% endfor %}						
					</tbody>
		</table>
    </div>
  </div> 

</div>


	<script type="text/javascript">
		$('.fact').submit(function(event){
											event.preventDefault();
											var form = $(this);
											$.post(form.attr('action'),
												   form.serialize(),
												   function(data){
												   					if (data.status){
												   						location.reload();
												   					}
												   					else{
												   						alert(data.msge);
												   					}
												   					
												   });

		});
	</script>
	